#ifndef UNIX_SOCKET_VERSION_H
#define UNIX_SOCKET_VERSION_H

#define UNIX_SOCKET_SNIFFER_VERSION_MAJOR 1
#define UNIX_SOCKET_SNIFFER_VERSION_MINOR 0
#define UNIX_SOCKET_SNIFFER_VERSION_PATCH 0

#endif
