"""HCCS traffic generator for testing.

This module provides tools to generate HCCS (Huawei Cache Coherence System)
traffic between NUMA nodes to test the HCCS bandwidth monitoring functionality.

HCCS traffic is generated by:
1. Allocating memory on one NUMA node
2. Accessing it from a CPU on another NUMA node
3. This causes cross-socket memory access via HCCS interconnect

Usage:
    python -m test.traffic.hccs_traffic --duration 10 --numa-node 0
"""

import argparse
import multiprocessing
import os
import time
from typing import List, Optional

import ctypes
import ctypes.util


def get_numa_nodes() -> List[int]:
    """Get available NUMA node IDs."""
    nodes = []
    node_base = "/sys/devices/system/node"
    if os.path.exists(node_base):
        for entry in os.listdir(node_base):
            if entry.startswith("node"):
                try:
                    node_id = int(entry.replace("node", ""))
                    nodes.append(node_id)
                except ValueError:
                    pass
    return sorted(nodes)


def get_cpus_on_numa(node_id: int) -> List[int]:
    """Get CPU IDs on a specific NUMA node."""
    cpus = []
    cpulist_path = f"/sys/devices/system/node/node{node_id}/cpulist"
    try:
        with open(cpulist_path) as f:
            cpulist = f.read().strip()
            for part in cpulist.split(","):
                if "-" in part:
                    start, end = part.split("-")
                    cpus.extend(range(int(start), int(end) + 1))
                else:
                    cpus.append(int(part))
    except (OSError, ValueError):
        pass
    return cpus


def bind_to_numa(node_id: int) -> bool:
    """Bind current process to a NUMA node using numactl-like functionality."""
    try:
        libc = ctypes.CDLL(ctypes.util.find_library("c"), use_errno=True)
        
        numa_set_preferred = libc.numa_set_preferred
        numa_set_preferred.argtypes = [ctypes.c_int]
        numa_set_preferred.restype = None
        
        numa_set_preferred(node_id)
        return True
    except Exception:
        pass
    
    cpus = get_cpus_on_numa(node_id)
    if not cpus:
        return False
    
    try:
        os.sched_setaffinity(0, set(cpus))
        return True
    except OSError:
        return False


def allocate_on_numa(node_id: int, size_mb: int) -> Optional[ctypes.Array]:
    """Allocate memory on a specific NUMA node."""
    try:
        # Try libnuma first (provides numa_alloc_onnode)
        libnuma = ctypes.CDLL("libnuma.so.1", use_errno=True)

        # Check if NUMA is available
        numa_available = libnuma.numa_available
        numa_available.restype = ctypes.c_int
        if numa_available() < 0:
            return None

        numa_alloc_onnode = libnuma.numa_alloc_onnode
        numa_alloc_onnode.argtypes = [ctypes.c_size_t, ctypes.c_int]
        numa_alloc_onnode.restype = ctypes.c_void_p

        size = size_mb * 1024 * 1024
        ptr = numa_alloc_onnode(size, node_id)

        if ptr:
            arr = (ctypes.c_char * size).from_address(ptr)
            return arr
    except Exception as e:
        pass

    return None


def free_numa_buffer(buffer: ctypes.Array, size_mb: int) -> None:
    """Free NUMA-allocated memory.

    Args:
        buffer: The ctypes array allocated by allocate_on_numa
        size_mb: Size of the buffer in MB
    """
    try:
        libnuma = ctypes.CDLL("libnuma.so.1", use_errno=True)

        numa_free = libnuma.numa_free
        numa_free.argtypes = [ctypes.c_void_p, ctypes.c_size_t]

        size = size_mb * 1024 * 1024
        ptr = ctypes.addressof(buffer)
        numa_free(ctypes.cast(ptr, ctypes.c_void_p), size)
    except Exception:
        pass  # Process exit will clean up anyway


def generate_cross_numa_traffic(
    src_node: int,
    dst_node: int,
    size_mb: int = 100,
    duration_sec: float = 10.0,
) -> dict:
    """Generate cross-NUMA traffic to create HCCS bandwidth.
    
    Args:
        src_node: Source NUMA node (where memory is allocated)
        dst_node: Destination NUMA node (where CPU accesses memory)
        size_mb: Size of memory buffer in MB
        duration_sec: Duration of traffic generation in seconds
    
    Returns:
        Statistics about the generated traffic
    """
    stats = {
        "src_node": src_node,
        "dst_node": dst_node,
        "size_mb": size_mb,
        "duration_sec": duration_sec,
        "bytes_accessed": 0,
        "iterations": 0,
    }
    
    def worker(src: int, dst: int, size: int, duration: float, result_queue):
        """Worker process that generates traffic.

        IMPORTANT: Memory must be allocated on src_node BEFORE binding CPU to dst_node.
        This ensures cross-NUMA access when CPU on dst_node accesses memory on src_node.
        """
        # Step 1: Allocate memory on src_node FIRST
        buffer = allocate_on_numa(src, size)
        if buffer is None:
            result_queue.put({
                "error": f"Failed to allocate {size}MB on node {src}. "
                         f"Ensure libnuma is installed " \
                         f"(apt install libnuma-dev / yum install numactl-devel)."
            })
            return

        buffer_size = size * 1024 * 1024

        # Step 2: NOW bind CPU to dst_node
        bind_to_numa(dst)

        start_time = time.time()
        bytes_accessed = 0
        iterations = 0

        while time.time() - start_time < duration:
            for i in range(0, buffer_size, 64):
                buffer[i] = chr((i // 64) % 256).encode()[0]
            bytes_accessed += buffer_size
            iterations += 1

        result_queue.put({
            "bytes_accessed": bytes_accessed,
            "iterations": iterations,
        })
    
    result_queue = multiprocessing.Queue()
    process = multiprocessing.Process(
        target=worker,
        args=(src_node, dst_node, size_mb, duration_sec, result_queue),
    )
    process.start()
    process.join()
    
    if not result_queue.empty():
        result = result_queue.get()
        if "error" in result:
            stats["error"] = result["error"]
        else:
            stats["bytes_accessed"] = result.get("bytes_accessed", 0)
            stats["iterations"] = result.get("iterations", 0)

    return stats


def generate_all_cross_numa_traffic(
    duration_sec: float = 10.0,
    size_mb: int = 100,
) -> List[dict]:
    """Generate cross-NUMA traffic between all NUMA node pairs.
    
    This creates HCCS traffic across all interconnect links.
    """
    nodes = get_numa_nodes()
    if len(nodes) < 2:
        print("Need at least 2 NUMA nodes for cross-NUMA traffic")
        return []
    
    print(f"Detected NUMA nodes: {nodes}")
    
    all_stats = []
    
    for i, src_node in enumerate(nodes):
        for dst_node in nodes[i + 1:]:
            print(f"\nGenerating traffic: node{src_node} <-> node{dst_node}")
            
            stats1 = generate_cross_numa_traffic(
                src_node, dst_node, size_mb, duration_sec
            )
            all_stats.append(stats1)
            
            stats2 = generate_cross_numa_traffic(
                dst_node, src_node, size_mb, duration_sec
            )
            all_stats.append(stats2)
    
    return all_stats


def generate_streaming_traffic(
    src_node: int,
    dst_node: int,
    size_mb: int = 100,
    duration_sec: float = 10.0,
) -> dict:
    """Generate streaming traffic (sequential access) between NUMA nodes.

    This simulates streaming data transfer patterns.

    IMPORTANT: Memory is allocated on src_node, CPU runs on dst_node.
    This creates cross-NUMA HCCS traffic from src_node -> dst_node.
    """
    stats = {
        "src_node": src_node,
        "dst_node": dst_node,
        "size_mb": size_mb,
        "duration_sec": duration_sec,
        "bytes_accessed": 0,
        "bandwidth_mbps": 0.0,
    }

    # Step 1: Allocate memory on src_node FIRST
    buffer = allocate_on_numa(src_node, size_mb)
    if buffer is None:
        stats["error"] = (
            f"Failed to allocate {size_mb}MB on node {src_node}. "
            f"Ensure libnuma is installed (apt install libnuma-dev)."
        )
        return stats

    buffer_size = size_mb * 1024 * 1024

    # Step 2: NOW bind CPU to dst_node
    bind_to_numa(dst_node)

    start_time = time.time()
    bytes_accessed = 0

    while time.time() - start_time < duration_sec:
        for i in range(buffer_size):
            buffer[i] = chr(i % 256).encode()[0]
        bytes_accessed += buffer_size

    elapsed = time.time() - start_time
    stats["bytes_accessed"] = bytes_accessed
    stats["bandwidth_mbps"] = (bytes_accessed / elapsed) / (1024 * 1024)

    return stats


def generate_random_traffic(
    src_node: int,
    dst_node: int,
    size_mb: int = 100,
    duration_sec: float = 10.0,
) -> dict:
    """Generate random access traffic between NUMA nodes.

    This simulates random memory access patterns that cause
    more cache misses and HCCS traffic.

    IMPORTANT: Memory is allocated on src_node, CPU runs on dst_node.
    This creates cross-NUMA HCCS traffic from src_node -> dst_node.
    """
    import random

    stats = {
        "src_node": src_node,
        "dst_node": dst_node,
        "size_mb": size_mb,
        "duration_sec": duration_sec,
        "bytes_accessed": 0,
        "accesses": 0,
    }

    # Step 1: Allocate memory on src_node FIRST
    buffer = allocate_on_numa(src_node, size_mb)
    if buffer is None:
        stats["error"] = (
            f"Failed to allocate {size_mb}MB on node {src_node}. "
            f"Ensure libnuma is installed (apt install libnuma-dev)."
        )
        return stats

    buffer_size = size_mb * 1024 * 1024

    # Step 2: NOW bind CPU to dst_node
    bind_to_numa(dst_node)

    start_time = time.time()
    bytes_accessed = 0
    accesses = 0

    cache_line_size = 64

    while time.time() - start_time < duration_sec:
        offset = random.randint(0, buffer_size - cache_line_size)
        for i in range(cache_line_size):
            buffer[offset + i] = chr(i).encode()[0]
        bytes_accessed += cache_line_size
        accesses += 1

    stats["bytes_accessed"] = bytes_accessed
    stats["accesses"] = accesses

    return stats


def main():
    parser = argparse.ArgumentParser(
        description="Generate HCCS traffic for testing bandwidth monitoring"
    )
    parser.add_argument(
        "--duration",
        type=float,
        default=10.0,
        help="Duration of traffic generation in seconds (default: 10)",
    )
    parser.add_argument(
        "--size",
        type=int,
        default=100,
        help="Size of memory buffer in MB (default: 100)",
    )
    parser.add_argument(
        "--src-node",
        type=int,
        default=None,
        help="Source NUMA node (default: all pairs)",
    )
    parser.add_argument(
        "--dst-node",
        type=int,
        default=None,
        help="Destination NUMA node (default: all pairs)",
    )
    parser.add_argument(
        "--pattern",
        choices=["streaming", "random", "all"],
        default="streaming",
        help="Traffic pattern (default: streaming)",
    )
    
    args = parser.parse_args()
    
    nodes = get_numa_nodes()
    print(f"Available NUMA nodes: {nodes}")
    
    if not nodes:
        print("No NUMA nodes detected. This tool requires a NUMA system.")
        return
    
    if args.src_node is not None and args.dst_node is not None:
        print(f"\nGenerating {args.pattern} traffic: node{args.src_node} -> node{args.dst_node}")
        
        if args.pattern == "streaming":
            stats = generate_streaming_traffic(
                args.src_node, args.dst_node, args.size, args.duration
            )
        elif args.pattern == "random":
            stats = generate_random_traffic(
                args.src_node, args.dst_node, args.size, args.duration
            )
        else:
            stats = generate_cross_numa_traffic(
                args.src_node, args.dst_node, args.size, args.duration
            )
        
        print(f"Results: {stats}")
    else:
        print(f"\nGenerating {args.pattern} traffic between all NUMA node pairs...")
        
        if args.pattern == "all":
            all_stats = generate_all_cross_numa_traffic(args.duration, args.size)
        else:
            all_stats = []
            for i, src in enumerate(nodes):
                for dst in nodes[i + 1:]:
                    if args.pattern == "streaming":
                        stats = generate_streaming_traffic(src, dst, args.size, args.duration)
                    else:
                        stats = generate_random_traffic(src, dst, args.size, args.duration)
                    all_stats.append(stats)
        
        print("\nSummary:")
        total_bytes = sum(s.get("bytes_accessed", 0) for s in all_stats)
        print(f"Total bytes accessed: {total_bytes / (1024**3):.2f} GB")
        
        for stats in all_stats:
            src = stats.get("src_node", "?")
            dst = stats.get("dst_node", "?")
            bw = stats.get("bandwidth_mbps", 0)
            print(f"  node{src} -> node{dst}: {bw:.2f} MB/s")


if __name__ == "__main__":
    main()
