#ifndef IPC_VERSION_H
#define IPC_VERSION_H

#define IPC_SNIFFER_VERSION_MAJOR 1
#define IPC_SNIFFER_VERSION_MINOR 0
#define IPC_SNIFFER_VERSION_PATCH 0

#define IPC_SNIFFER_VERSION \
    ((IPC_SNIFFER_VERSION_MAJOR << 16) | \
     (IPC_SNIFFER_VERSION_MINOR << 8) | \
     IPC_SNIFFER_VERSION_PATCH)

#endif
